### ISSUE TITLE
UnitFrames - Add mount's health

### ISSUE THREAD

**Issue by adamjedlicka** [ForgeUI/ForgeUI#1]

**Comment by codemasher** [comment]
Dang, this is one of the things i wanted to request. Any chance thi is going to make it into ForgeUI one day?

**Comment by Peshyy** [comment]
Yes please! :D Also, if you could add the Markbot HP for Scientists :3

**Comment by adamjedlicka** [comment]
Not yet. It not necessary and I think it's ruins clean design of ForgeUI. Maybe someday if I have some idea how to implement it nicely but definitely not like another UnitFrame
