### ISSUE TITLE
Tooltips - Error

### ISSUE THREAD

**Issue by adamjedlicka** [ForgeUI/ForgeUI#104]
...ildStar\Addons\ForgeUI_ToolTips\ForgeUI_ToolTips.lua:197: attempt to index field 'wndUnitTooltip' (a nil value)
stack trace:
	...ildStar\Addons\ForgeUI_ToolTips\ForgeUI_ToolTips.lua:197: in function 'UnitTooltipGen'
	ui\ToolTips\ToolTips.lua:2466: in function <ui\ToolTips\ToolTips.lua:2464>

**Comment by frozoingo** [comment]
got the same bug as above, running with forgeui, kurona bags and taxi mute addons

...ildStar\Addons\ForgeUI_ToolTips\ForgeUI_ToolTips.lua:197: attempt to index field 'wndUnitTooltip' (a nil value)
stack trace:
...ildStar\Addons\ForgeUI_ToolTips\ForgeUI_ToolTips.lua:197: in function 'UnitTooltipGen'
	ui\ToolTips\ToolTips.lua:2466: in function <ui\ToolTips\ToolTips.lua:2464>
