### ISSUE TITLE
Inventory - Automatically sell junk and repair when talking to vendor

### ISSUE THREAD

**Issue by mkaito** [ForgeUI/ForgeUI#116]

**Comment by adamjedlicka** [comment]
I was considering it, but there's already addon for it (JunkIt) and primarĺy I don't want to add features to ForgeUI which can be added with other addons. But on the other side this is really basic and handy functionality so I will consider it.

**Comment by mkaito** [comment]
Well you can always make it optional so it doesn't clash with people who already use junkit? Also, junkit hasn't been updated in a while, so unless the maintainer comes back it's bound to become obsolete sooner or later as the API changes.

**Comment by mkaito** [comment]
Well, I guess this is taken care of :stuck_out_tongue:
