### ISSUE TITLE
Better component reposition

### ISSUE THREAD

**Issue by mkaito** [ForgeUI/ForgeUI#118]
Things I have in mind (with no knowledge of whether they might be impossible due to API, but here goes proposing anyway):

* Selecting and moving multiple components at the same time.
* Selecting and scaling multiple components at the same time.
* Snap to grid.
* Snap to screen edge.
* Keyboard nudge (ie, use arrow keys to move a single pixel, or 10 pixels with shift+arrow).

It would probably be useful to remove any padding from components like action bars for this to be more useful.

Aside: I don't want to open a github issue for random questions. Should I post those on Curse, or can I email/irc you instead?

**Comment by adamjedlicka** [comment]
Thanks for feedback really appreciate it, but:
Keyboard nudge is impossible to do. Atm if you right click any mover clickable nudge will appear.
And 1, 2, 3, 4 are not impossible but really hard to do. Mainly complicated mathematics which I'm not good at. So I'm not planning to do none of these atm but maybe in the future or if someone will be willing to do it. Most realistic is snapping windows to grid and I already have this request opened here in the GitHub issues.

About your questions. Post it on curse. I check it there multiple times a day so I will notice it sooner.
