### ISSUE TITLE
ResourceBars - Error

### ISSUE THREAD

**Issue by adamjedlicka** [ForgeUI/ForgeUI#122]
...Addons\ForgeUI_ResourceBars\ForgeUI_ResourceBars.lua:303: attempt to index a nil value
stack trace:
	...Addons\ForgeUI_ResourceBars\ForgeUI_ResourceBars.lua:303: in function 'OnMedicCreated'
	...Addons\ForgeUI_ResourceBars\ForgeUI_ResourceBars.lua:178: in function <...Addons\ForgeUI_ResourceBars\ForgeUI_ResourceBars.lua:162>

**Comment by Toludin** [comment]
I can't reproduce this on a Medic (tried both existing and a brand new player). Where'd you see it?

**Comment by adamjedlicka** [comment]
That's not from me. Happened once to our GM. I think I should create a label for those weird errors that appeared only once or twice.

**Comment by Toludin** [comment]
Agreed, it might be nice to track the reliably reproducible bugs a bit separately from the one-offs that you want to have documented in case they are seen again.
