### ISSUE TITLE
ActionBars - Warplot special bar is missing

### ISSUE THREAD

**Issue by adamjedlicka** [ForgeUI/ForgeUI#123]
I have no idea what this mean but few ppl already reported it. I will try to get into warplot today to check it out.

Apparently it should be visible all the time in warplot and should server for upgrading buildings and stuff.

**Comment by NyntoFive** [comment]
It works outside of the match, just like the housing bar.  But in the actual match, the 'Warplot Ability Bar' does not load.  You cannot activate your superweapon/upgrade/load boss tokens or any warplot functionality in the actual match.  If you need to get in an actual match, just lemme know we've been running them every Saturday night @8est.  Contact Nyn Tofive (exile) or Scarling Darkspyre (dominion).
