### ISSUE TITLE
Nameplates - level indicator shows "nil"

### ISSUE THREAD

**Issue by codemasher** [ForgeUI/ForgeUI#124]
The level indicator in the Nameplates addon shows "nil" value on creatures without a level. Just have a look at the Rowsdowers near the Tremor Ridge Taxi in Algoroc. The default Nameplate shows something like a hyphen or a dot instead.

**Comment by Toludin** [comment]
I've noticed this as well. I agree that 'nil' is probably not the best thing to show in these cases.

I'll check out what the default UI shows and change it to something like that. Adam, let me know if there's anything specific you'd like to use (or if you'd like to make this change yourself).

**Comment by adamjedlicka** [comment]
I don't think it extra important what it shows. I think nothing would be best but it really doesn't matter.

**Comment by codemasher** [comment]
A number zero would be most consistent i guess.
