### ISSUE TITLE
FloatText: show absorption amount

### ISSUE THREAD

**Issue by Toludin** [ForgeUI/ForgeUI#125]
As mentioned on Curse:
> On Water-Air el pair, while tsunami phase, you can't see floating text at all (ur dmg to absorb). With Carbines combat text it's something like 'Absord 1000', 'Absord 2000'

This seems to be a result of not calculating Total Damage to include absorbed amount (ForgeUI_FloatText.lua:143-146), resulting in the Total Damage being below threshold.

Options include:
 1. Include absorbed damage in the Total Damage calculation.
 2. Separate out each Damage type and either:
  * Allow user control over which elements to include in the Total Damage calculation.
  * Report each as a separate value to the user in some fashion (different colors, for example)
 3. Leave as-is.

I do think it's a good idea to include Absorb, but 1 vs 2 really comes down to the overall direction/plan for FloatText. Let me know what you think - I would be happy to implement either, if you're not already working on this.

**Comment by adamjedlicka** [comment]
Yeah. This is bothering me for some time now, but for some reason didn't fix it. I was planning just adding absorbed damage to the total damage calculation:

```lua
if type(nAbsorptionAmount) == "number" and nAbsorptionAmount > 0 then
    nTotalDamage = nTotalDamage + nAbsorptionAmount
```

This should do the job. First if is already there so just add that calculation behind it. It has to be changed in OnDamageOrHealing() and OnPlayerDamageOrHealing()
