### ISSUE TITLE
Profiles for Nameplates

### ISSUE THREAD

**Issue by Ranjero** [ForgeUI/ForgeUI#135]
Hey love the addon and your name plates but there are times especially for raids when it would be awesome to quick swap saved profiles for nameplate settings. I like seeing group member nameplate health in the world and dungeons but come raid time I'd be great to quick swap them off off to save frames and clutter. There are probably other features of the addon pack that could benefit from profiles too like lay out of UI. Keep up the good work :)

**Comment by adamjedlicka** [comment]
There will be profiles in v0.5
