### ISSUE TITLE
UnitFrames - Player Level?

### ISSUE THREAD

**Issue by czbaker** [ForgeUI/ForgeUI#139]
I don't know if this is an existing option that I'm missing, or if it's a plan or something, but is there a way to get the player level (class not required) on the player's unit frame?  

The only other way to acquire level is through permanently visible nameplates, and it seems that there's a current bug with the ForgeUI nameplates that requires me to manually `/reloadui` when I gain a level to update my visible level.

**Comment by Toludin** [comment]
You can view your level under the Titles page of the Character panel. But considering how many people have asked/requested this, it's probably something to add as well.

**Comment by adamjedlicka** [comment]
Yeah, I will be adding this in v0.5

**Comment by czbaker** [comment]
That's awesome.  Is there any fix in the works for the nameplate update problem?

**Comment by adamjedlicka** [comment]
Nameplate update problem? If you mean slow updating of nameplates just check Fast updates under nameplates > general in main ForgeUI window
