### ISSUE TITLE
UnitFrames - Targeting certain objects/targets crash ForgeUI_UnitFrames

### ISSUE THREAD

**Issue by acira** [ForgeUI/ForgeUI#141]
Targeting certain objects crash ForgeUI_UnitFrames (0.5-alpha).

Eg. Thayd Guild Banker, Mailbox, Personal Depositron

...tar\Addons\ForgeUI_UnitFrames\ForgeUI_UnitFrames.lua:448: attempt to perform arithmetic on a nil value
stack trace:
	...tar\Addons\ForgeUI_UnitFrames\ForgeUI_UnitFrames.lua:448: in function 'RefreshStyle'
	...tar\Addons\ForgeUI_UnitFrames\ForgeUI_UnitFrames.lua:227: in function 'UpdateTargetFrame'
	...tar\Addons\ForgeUI_UnitFrames\ForgeUI_UnitFrames.lua:202: in function 'UpdatePlayerFrame'
	...tar\Addons\ForgeUI_UnitFrames\ForgeUI_UnitFrames.lua:178: in function <...tar\Addons\ForgeUI_UnitFrames\ForgeUI_UnitFrames.lua:174>

**Comment by adamjedlicka** [comment]
Cause by gradient settings
