### ISSUE TITLE
Nameplates - names do not re-color to normal on either leaving a group, nor a member leaving

### ISSUE THREAD

**Issue by Toludin** [ForgeUI/ForgeUI#144]
When another player in your group leaves, or you leave a group, the name on their nameplate stays the "in party" color.

**Comment by adamjedlicka** [comment]
Its not only color. Whole 'tNameplate.strUnitType' doesn't change, so your options in settings doesn't work if this happens. Maybe some event listener when player joins/leave the group and change their 'tNameplate.strUnitType'

**Comment by Toludin** [comment]
Good to know. Probably want to listen for Group_Left() (for the player) and Group_Remove() (for another player).
