### ISSUE TITLE
Nameplates - Bugs

### ISSUE THREAD

**Issue by reddy89** [ForgeUI/ForgeUI#151]
1. Nameplates vibrate sometimes. Probably due to move nameplates to feet option. Doesn't always happen, but enough to be annoying. When it does happen, panning your camera in any direction will not get rid of it. Even dragging your camera all the way down it still does it. So it doesn't just happen at the threshold where the nameplate are supposed to go to the feet.
Video: http://www.twitch.tv/redward_tv/c/6973656

2. Health bar eats right click action and prevents camera movement as a result. Even when you disable health bars (I do for friendlies), it still eats the right click where the health bar is supposed to be. Pretty frustrating in larger group content or open world events where there are a lot of people and I can't pan my camera.

**Comment by adamjedlicka** [comment]
1. I know about this and seen it few times but I'm not able to replicate it to see whats causes it.
2. You can disable this in options. Just uncheck 'Clickable nameplates' under the general tab.

**Comment by reddy89** [comment]
Can you make clickable nameplates work with just left click and not right click?

**Comment by adamjedlicka** [comment]
I think its possible, but I'm not sure. If stock nameplates support it than it's possible for sure.

**Comment by Toludin** [comment]
Since there's an eMouseButton parameter passed on the MouseButtonDown event, I imagine you can use this to filter on a certain mouse button, if desired.

**Comment by reddy89** [comment]
OptiPlates does it. I believe Carbine ones do to? Haven't used those in ages though.
