### ISSUE TITLE
InterfaceMenuList - Moveable

### ISSUE THREAD

**Issue by TheBloodEagle** [ForgeUI/ForgeUI#154]
As I game using 3 screens, Wildstar has always placed UI elements all over the place. Your UI is amazing, and gives me huge amounts of control over my UI except in three cases.

Would it be possible to make your menu bar at the bottom left corner moveable? The other two elements are not yours, but would make many people happy if they could also be moved, so my other question is Could you make the default quest tracker and default tooltip moveable as part of ForgeUI?

Thank you for your consideration.

**Comment by Peshyy** [comment]
You know, you can move almost every single element of the UI by default, without any addons required. Just go to Interface

and then Positioning ![Positioning menu](http://puu.sh/j7aKb/b788c67d1a.jpg)

You can see the Objective Tracker there :)

**Comment by Toludin** [comment]
I know Winty is working on making the menu bar moveable (or at least adding options for selecting where it appears). As for the Objective Tracker, I think Peshyy's suggestion is probably the best.

**Comment by Peshyy** [comment]
Hmm, can't you move the bar from the ForgeUI? I think it's the same as the Radiance or whatever it's called, try unlocking the UI and see what you can move (sorry, I'm not using ForgeUI atm, so I can't tell exactly how it's called ;/)

**Comment by TheBloodEagle** [comment]
Once unlocked, the sprint bar and Dash bar can be moved, but not the breath bar.

Thanks for your help, I will put in a new ticket about it.

**Comment by Peshyy** [comment]
Good luck! Hope it gets resolved :)

**Comment by adamjedlicka** [comment]
Yeah hazards (breath, ...) are atm unmovable. I'll do something about it soon.

**Comment by Mae-Is-Mean** [comment]
Bumping, because the InterfaceMenuList is still unmoveable, and this would be such a BIG change for me. Is this still being worked on?

**Comment by Mischh** [comment]
If I did not miss anything, this should be resolved with this Commit: 3c1753079c011b32246bbd0a58f77373c05edcea

-Mischh
