### ISSUE TITLE
Breath Bar: Unable to be repositioned

### ISSUE THREAD

**Issue by TheBloodEagle** [ForgeUI/ForgeUI#155]
When unlocking the ForgeUI elements, I am unable to move the breath bar, which is stuck on my left monitor all by itself.  :(

![bloodeagle_starforge 150721 065809](https://cloud.githubusercontent.com/assets/10183890/8808689/2282f13c-2fb2-11e5-851d-9c1ddec7af67.png)

![bloodeagle_starforge 150721 140351](https://cloud.githubusercontent.com/assets/10183890/8808694/252ed77a-2fb2-11e5-995a-7f04dcb0eed9.png)

![bloodeagle_starforge 150721 140419](https://cloud.githubusercontent.com/assets/10183890/8808695/279c5c12-2fb2-11e5-9be5-95263b99d3ec.png)

Thanks for the great UI!

**Comment by Toludin** [comment]
Fixed in upcoming version.
