### ISSUE TITLE
Guild Holomarks

### ISSUE THREAD

**Issue by NekoNova** [ForgeUI/ForgeUI#156]
Heya,

Not sure if this is an issue with ForgeUI, but trying to narrow it down.
So my question:  Does ForgeUI hide Guild Holomarks on players? Cause mine stopped showing up when I started using this Addon.

**Comment by adamjedlicka** [comment]
No. ForgeUI doesn't do anything with holo marks. Their settings is in Character window ( C ) under the Titles tab. You can show/hid them there.

**Comment by NekoNova** [comment]
Yeah that's the thing, the settings ain't do anything so something is interfering with their display.
But if ForgeUI is not involved with this I will continue my search.
Thanks for answering.
