### ISSUE TITLE
Nameplate suggestions

### ISSUE THREAD

**Issue by Vivolus** [ForgeUI/ForgeUI#157]
I love foregui, but I think the weakest part of the addon is it's nameplates. That being said, I still use them anyway because I like them more than anything else I have used :) Some things I would love to see to improve name plates are:

1) Be able to adjust the location/height of the cast bars below the nameplate. The current cast bars gets cut off by the health/shield bar. I would like to be able to see the cast name. 

2) Be able to adjust the location of the nameplate on tall enemies but position it at the very top of the screen. I like to see my parties health pools and any debuffs on them and making this an option will allow me to see my teams health and enemies health minimal clutter. 

3) Targeted nameplate always on top option. Self explanatory. 

4) Being able to change the size of enemies and players nameplates separately.

5) Icon for debuffs option. Sometimes it is nice to see who in your party has a debuff on them but I don't want the added clutter of seeing there health bar with it as well. 

Keep up the great work, don't want to play the game without it.

**Comment by adamjedlicka** [comment]
Thanks for the feedback. I will start developing ForgeUI again when PTR hits, so most of this should be availible at the same time as Drop 6.

Can you please explain request number 2? You don't want nameplates to be aboe heads of the players but on the top of the screen?

**Comment by Vivolus** [comment]
No, #2 has to do with Hostile Npc nameplates. I did not make that very clear before. I can see this coming in handy on bosses where you have to stack on the bosses butt. I would like to be able to see my parties health bars as well as hostile npc health bars. So, If I preposition the hostile npc health bar as of now, because he is too tall, the health bar goes down to its feet, the same area where my parties health bars are. So I would like to see an option where instead of the hostile npc health bar gets re positioned by its feet, because its too tall, but rather get re positioned at the very top of the screen. This way i can see all my parties health bars and boss health bar without it getting lost among the others. 

Either that or make a feature like optiplates where its variable and you can tinker around with it to be re positioned where you want it. 

I would love to see this feature but I do not think it is an absolute must. Just adds some more flavor to nameplates.

**Comment by adamjedlicka** [comment]
Ok I understan it now. Unfortunatelly it won't be possible to do without huge FPS loss.

**Comment by Vivolus** [comment]
Ahh nbd. Glad to see you are still going to be working on it :)
