### ISSUE TITLE
UnitFrames - Class colors

### ISSUE THREAD

**Issue by dvlsg** [ForgeUI/ForgeUI#160]
I would love to see some functionality similar to the bClassColors logic utilized by ForgeUI_Nameplates ported over to ForgeUI_UnitFrames for the background color of the unit frames.

**Comment by repsejnworb** [comment]
Doooo want.
First thing I thought when I installed this.

**Comment by adamjedlicka** [comment]
Will be in v0.5

**Comment by themadtux** [comment]
Yeah would love to see this added as well.  Love the dark look of the current colors (reminds me of Tukz/ElvUI from WoW) but would love to have the option of class color as well :)

**Comment by dvlsg** [comment]
:+1: That sounds fantastic. Thanks for the heads up, I'll be keeping an eye out!

**Comment by repsejnworb** [comment]
Nice news. Looking forward to v0.5 !
