### ISSUE TITLE
ActionBars - Las bug

### ISSUE THREAD

**Issue by bbnn12** [ForgeUI/ForgeUI#162]
There seems to be a problem in the Action bars, since my LAS wasnt saving when i try to rearrange them turn the forge ui main addon and action bar addon off and t worked again, i was able to save my LAS

**Comment by mrkidsam** [comment]
I had this issue as well but I believe it was because I was trying to copy my Forge save data from one character to another, just to save myself a few hours of setting it up again and again. But I couldnt seem to figure out a way to copy it over without it locking my amp and abilities.

**Comment by adamjedlicka** [comment]
@mrkidsam yeah, if you copy settings from one char to another and it locks your LAS just reset ActionBars settings in main ForgeUI windows > Addons button (bottom right) > ActionBars > Reset settings. That will fix it.

**Comment by satch3l** [comment]
I also have had issues with the action bar. On 1 of my 3 chars (Warrior) I was unable to change, upgrade or add skills and amps. All I got was an error message which told me "This set could not be activated".

**Comment by adamjedlicka** [comment]
Duplicate with #209
