### ISSUE TITLE
NeedGreed - Error on login

### ISSUE THREAD

**Issue by Flupperich** [ForgeUI/ForgeUI#163]
Getting this error message from time to time, most often after just logging in

...dStar\Addons\ForgeUI_NeedGreed\ForgeUI_NeedGreed.lua:143: attempt to index a nil value
stack trace:
	...dStar\Addons\ForgeUI_NeedGreed\ForgeUI_NeedGreed.lua:143: in function <...dStar\Addons\ForgeUI_NeedGreed\ForgeUI_NeedGreed.lua:142>

**Comment by Toludin** [comment]
I guess we need to increase the PlayerNameCheckTimer counter then (line 80). It's an error when we try to grab the player's name, but that value hasn't initialized yet.

**Comment by adamjedlicka** [comment]
I would check if GameLib.GetPlayerUnit() is nil and if yes start the PlayerNameCheckTimer again. Doesn't need to be propper fix. In v0.5 is this solved by proper timing of ForgeUI addons loading.

**Comment by Toludin** [comment]
:-)

Yup that would probably be a smarter way to handle the race condition.

**Comment by adamjedlicka** [comment]
FIxed in v0.4.6a
