### ISSUE TITLE
Targeting data cubes and lore objects deactivates righ-click look

### ISSUE THREAD

**Issue by satch3l** [ForgeUI/ForgeUI#165]
When I am targeting either a data cube or a lore object I cannot use the right mouse button to look around.

**Comment by adamjedlicka** [comment]
Can you explain it a little bit more, please?

**Comment by satch3l** [comment]
If I'm walking up to a datacube for example. If I'm selecting/targeting it I cannot hold down right mouse button in order to look around with the camera. I can still use the left mouse button to look around though. And this happens when I'm selecting objects like a datacube or lore objects in the world.

**Comment by adamjedlicka** [comment]
Interesting... Does it show context menu when you right click? Or anythin weird happens? I'm unable to reproduce it.
