### ISSUE TITLE
MiniMap - Error

### ISSUE THREAD

**Issue by adamjedlicka** [ForgeUI/ForgeUI#170]
...\WildStar\Addons\ForgeUI_MiniMap\ForgeUI_MiniMap.lua:1137: attempt to get length of field 'tQueuedUnits' (a nil value)
stack trace:

**Comment by angelcynn9** [comment]
...\WildStar\Addons\ForgeUI_MiniMap\ForgeUI_MiniMap.lua:1137: attempt to get length of field 'tQueuedUnits' (a nil value)
stack trace:
	...\WildStar\Addons\ForgeUI_MiniMap\ForgeUI_MiniMap.lua:1137: in function <...\WildStar\Addons\ForgeUI_MiniMap\ForgeUI_MiniMap.lua:1133>


Loading into game creates the error, minimap shows, seems to function. Options however do not seem possible to activate within ForgeUI options.

**Comment by Althena** [comment]
Complete Failure:
...\WildStar\Addons\ForgeUI_MiniMap\ForgeUI_MiniMap.lua:1137: attempt to get length of field 'tQueuedUnits' (a nil value)
stack trace:
	...\WildStar\Addons\ForgeUI_MiniMap\ForgeUI_MiniMap.lua:1137: in function 'OnUnitCreated'
	...\WildStar\Addons\ForgeUI_MiniMap\ForgeUI_MiniMap.lua:1315: in function <...\WildStar\Addons\ForgeUI_MiniMap\ForgeUI_MiniMap.lua:1307>
