### ISSUE TITLE
Inventory - Salvage Error

### ISSUE THREAD

**Issue by wheatbread** [ForgeUI/ForgeUI#173]
With v0.4.6c that is currently on github, I receive the following error when clicking on the Salvage button in the inventory:

...ildStar\Addons\Gear_ItemsSecure\Gear_ItemsSecure.lua:361: attempt to index a nil value
stack trace:
	...ildStar\Addons\Gear_ItemsSecure\Gear_ItemsSecure.lua:361: in function <...ildStar\Addons\Gear_ItemsSecure\Gear_ItemsSecure.lua:335>
	(tail call): ?
	[C]: in function 'Event_FireGenericEvent'
	...ar\Addons\ForgeUI_Inventory\ForgeUI_InventoryBag.lua:526: in function <...ar\Addons\ForgeUI_Inventory\ForgeUI_InventoryBag.lua:525>

**Comment by eetumans** [comment]
I was supposed to mention this yesterday as well but forgot. There seems to be some clash with the gear set saver addon "Gear" http://www.curse.com/ws-addons/wildstar/227981-gear and more specifically it's option of 'Item Protection' or something along those lines which hides items that are saved as a part of a set from salvage, vendor, etc. Temporary workaround would be to disable the item protection and then both still play nice together. It's a nice feature though and I would like to see these addons play together!

**Comment by mkaito** [comment]
This is indeed a really nice feature, as ItemSecure enables you to hide set gear from vendors and salvage, as well as preventing deletion.

Any chance the authors work together on this?

**Comment by adamjedlicka** [comment]
Yeah Its my bad its not working. I wll try to find some time as soon as possible to fix it.

**Comment by daorven** [comment]
Hi,

Not really author fault, just code come from 'Gear' and 'ForgeUI' not the same, a missing line come after a fresh Crabine update.
