### ISSUE TITLE
Right Click Look Problems and random Buff Frame?

### ISSUE THREAD

**Issue by bbnn12** [ForgeUI/ForgeUI#176]
1) right click problem: randomly after clicking something the right click look will be disabled and and everytime i right click a menu appears as if im right clicking my own character frame

2) also a random buff or de buff bar that ic ant mvoe on bottom right (with pic)
![image](https://cloud.githubusercontent.com/assets/14913112/10324601/dbd1039e-6c58-11e5-977e-7334e074fe92.png)

**Comment by reddy89** [comment]
1. Yea there seems to still be some oddities with right click even in the latest release.

2. Those buffs/debuffs are from LUI aura. Gotta go in there and disable the bars.
