### ISSUE TITLE
Action Bars - Runic Healing - Bug

### ISSUE THREAD

**Issue by dbush2765** [ForgeUI/ForgeUI#177]
Seeing a weird error on my Spellslinger. I have to disable the addon to put Runic Healing on my bars. I also noticed that when the addon is on, Runic Healing takes the place of whatever Path ability I have set, with no way to change it. This only seems to happen with Runic Healing for some reason.

**Comment by adamjedlicka** [comment]
I'll look at it.

**Comment by Newbieshoes** [comment]
Applies to Wild Barrage as well.  And Atomic Surge for Warriors.

**Comment by Toludin** [comment]
I can't seem to reproduce this issue. Anyone have a screenshot or video showing the problem?

**Comment by adamjedlicka** [comment]
Dupicate #209
