### ISSUE TITLE
Mount and Potion Button

### ISSUE THREAD

**Issue by Malkom** [ForgeUI/ForgeUI#179]
Hi,

A little problem on the last version :  buttons for mounts and potions not working.

Work fine if ForgeUI actionBars are disabled

**Comment by mkaito** [comment]
They sometimes disappear on me as well. A `/reloadui` usually fixes it, but it's mildly annoying.

**Comment by Malkom** [comment]
A reloadui never work for me...

**Comment by adamjedlicka** [comment]
You can also try right-clicking your innate button. Ir is your mount and potion button 100% unfunctional?

**Comment by Malkom** [comment]
I can see the innate button with ForgeUI and right-clicking on the button of ForgeUI doesn't work (indeed I think but i can't test amt) but I'm sure that the keybinding doesn't work.

**Comment by Malkom** [comment]
I'm very sorry but I can try this morning and you're right : with right-clicking button I can configure mount and potion.

So it's works perfectly !!! :)

Sorry again and sorry for the double post ;)
