### ISSUE TITLE
ActionBars - Vehicle bar missing

### ISSUE THREAD

**Issue by wheatbread** [ForgeUI/ForgeUI#181]
Hi,

I've run into some quests where the action bar should show the special actions for the quest when using a 'vehicle' or 'quest item' of sorts, but it doesn't.  I've had to enable the default action bar to access the special actions.

Ex. 

1. The Data Mining quest in Celestion: http://www.jabbithole.com/quests/data-mining-7027  
-->  Once you click the Datapad Inferface, the action bar should have 3 buttons: Transfer, Copy, and Deprecate. 

2. The Making of a Matria quest: http://www.jabbithole.com/achievements/episode-completion-the-making-of-a-matria-2362
--> once they turn you into a vind, your action bar should show: Vind Tracking Sense, Dig, Jump, Dismount

**Comment by adamjedlicka** [comment]
Is this v0.5 or v0.4? If v0.5 then I know about it.

**Comment by wheatbread** [comment]
Sorry, I forgot to say it's v0.5.
