### ISSUE TITLE
Nameplates - Show only for objectives

### ISSUE THREAD

**Issue by qsauce** [ForgeUI/ForgeUI#182]
I was wondering it it would be possible to have an option to only have NPC nameplates show when you have a quest.  Example would be you have all nameplates off and if you have a quest to kill say chompas then only the mobs related to that quest would havevisible names plates and all other mobs would be hidden, same as if you have no quests then all NPC nameplates would be hidden in the world.

The only addon that I know of currently that does this is Steadyplates but that requires the default namplates to be running, all other nameplate addons seem to omit this option. I was wondering it this is a possible addition that could be made or if it isnt possible with the current setup.

**Comment by adamjedlicka** [comment]
I'll look at it. This should be working in v0.4 and v0.5 but probabbly isnt.
