### ISSUE TITLE
Scaling Names/Nameplates

### ISSUE THREAD

**Issue by Polyrhythmz** [ForgeUI/ForgeUI#183]
First of all thank you for this addon!

My request is for names/nameplates to scale with distance. This is a common feature in other mmo's that help to massively reduce clutter and increase clarity. Thank you :)

**Comment by adamjedlicka** [comment]
PerspectivePlates now added support for this: http://www.curse.com/ws-addons/wildstar/221317-perspectiveplates

**Comment by Polyrhythmz** [comment]
Thank you!
