### ISSUE TITLE
Nameplates: Threat bar

### ISSUE THREAD

**Issue by mkaito** [ForgeUI/ForgeUI#188]
Attach a bar to the health bar to represent threat. If you have aggro, the bar should represent the threat of the next person. If you do not have aggro, it should represent your threat level relative to whoever has aggro.

This would largely negate the need for bulky threat meter addons.

**Comment by adamjedlicka** [comment]
Sorry, I'm not gonna do this. It would increase clutter in the nameplates, make it more CPU intensive and it's not important. You can over aggro on trash without any big consequences and on bosses you have propper threat meter.

**Comment by mkaito** [comment]
Fair enough. Nameplates are by far the hoggiest part of the interface, after all. I do not agree on the clutter, though. It should only appear in combat anyway.
