### ISSUE TITLE
Import/Export settings

### ISSUE THREAD

**Issue by mkaito** [ForgeUI/ForgeUI#190]
I just spent 40 minutes setting everything up again on a new character. Yesterday I spent some 30 minutes setting my main up again after transferring servers.

Exporting settings for backup purposes should be useful, and importing them should also be useful for sharing across characters.

Edit: I'm guessing that the API won't let you mess with files, so this might be complicated. But can addon settings files be copied around freely?

**Comment by adamjedlicka** [comment]
In v0.4 you have to copy ForgeUI_0_Char.xml in %appdata%/wildstar/addonsavedata . In v0,5 this is fully implemented right into the ForgeUI.
