### ISSUE TITLE
Unitframes - Portraits

### ISSUE THREAD

**Issue by Kobrakaj** [ForgeUI/ForgeUI#193]
Could you put in an options to have portraits for the Player & Target unitframes? I absolutely love ForgeUI but because I find portraits absolutely essential to my playing experience I had to download PotatoUI and use those unitframes instead.

**Comment by ElizGwen** [comment]
I dont think its possible, but if u could just enable target portrait frames -Without your own- optional or not versions, hideable during combat would be great but then again i dont think that's possible.

Then again just a version with frames would make many happy. Thx.

**Comment by adamjedlicka** [comment]
Duplicate with #8
