### ISSUE TITLE
ForgeUI - Tooltips

### ISSUE THREAD

**Issue by Sephirox** [ForgeUI/ForgeUI#194]
stack trace:
...SOFT\WildStar\Addons\CommodityStats\Transactions.lua:95: in function 'trim'
...NCSOFT\WildStar\Addons\CommodityStats\Statistics.lua:36: in function 'GetLatestStatForItemid'
...FT\WildStar\Addons\CommodityStats\CommodityStats.lua:354: in function 'origGenerateItemTooltipForm'
...ildStar\Addons\ForgeUI_ToolTips\ForgeUI_ToolTips.lua:166: in function 'GetItemTooltipForm'
...NCSOFT\WildStar\Addons\KuronaSachel\KuronaSachel.lua:138: in function <...NCSOFT\WildStar\Addons\KuronaSachel\KuronaSachel.lua:105>

**Comment by Toludin** [comment]
How are you reproducing this? Do you get an error when the ForgeUI Tooltips addon is disabled?

**Comment by Sephirox** [comment]
I will replicated once I am home and post it; but I beleive it might be CommodityStats now thought; weird this did not happen yesterday thought. It started happening after I updated to the .5 Beta of ForgeUI then it was constantly crashing the minimap so I had to revert back. Will post if I find anything more. Also where can I post for the Beta feedback? Since the only thing crashig constantly when I updated was the minimap even when resseting settings.

Sincerely,

Juan Alvarez

**Comment by Toludin** [comment]
Yea I also think it's due to CommodityStats, but try reproducing without ForgeUI Tooltips and see how that goes.

As far as beta feedback, I'm not sure if there's a specific section for it really. The page on curse.com might be the most prevalent place for general feedback.

**Comment by jcdenton2k** [comment]
I don't know how many times I'll have to repeat this shit.
DISABLE ALL OTHER ADDONS WHEN REPORTING BUGS!  The only addons should be CARBINE and ForgeUI addons enabled!
FFS....these people.
