### ISSUE TITLE
Missing Mail and Daily Reward from Interface Menu List

### ISSUE THREAD

**Issue by Vortelf** [ForgeUI/ForgeUI#198]
![image](https://cloud.githubusercontent.com/assets/8501971/10575512/9005af84-7665-11e5-8c36-26d1c3052345.png)

**Comment by Toludin** [comment]
Hmm, shows up on mine. What version are you running? If you make a new character, does it show up there?

**Comment by Vortelf** [comment]
Version 0.4.6c

**Comment by jcdenton2k** [comment]
I see you're using other addons.  Only have Carbine & ForgeUI addons and try again.
ForgeUI is not responsible for ensuring full compatability with every other addon out there :P
