### ISSUE TITLE
Medic skill "Empowering Probes" bugged

### ISSUE THREAD

**Issue by Jinivus** [ForgeUI/ForgeUI#199]
Odd one, but the Medic Utility skill "Empowering Probes" exhibits the following behavior only whilst the ForgeUI_ActionBars module is enabled.

The skill is listed as being at base level in the Action Set Builder, even when it is not. The remove button cannot be used to remove it from the current Action Set(Because it isn't really there to begin with I guess). This leads to the skill basically being unable to be used, because I cannot add it to my Action Set.
When I disable ForgeUI_ActionBars and Reload UI, everything works fine and the Action Set Builder displays it properly, allowing me to add it to the current Action Set.

This sounds confusing so I've uploaded a quick video to youtube demonstrating the bug. Unfortunately my mouse isn't recorded, but you can still see what I mean I think.
https://www.youtube.com/watch?v=e-S8E0R04Wc

**Comment by Toludin** [comment]
I can't reproduce this issue on my Medic.

Can you try resetting and seeing if it's still reproducible? And did you happen to copy your settings from another character?

**Comment by adamjedlicka** [comment]
Duplicate with #209
