### ISSUE TITLE
Nameplates - Add aggro indicator

### ISSUE THREAD

**Issue by adamjedlicka** [ForgeUI/ForgeUI#2]

**Comment by adamjedlicka** [comment]
v0.3.5

**Comment by reddy89** [comment]
Does this actually work? I tried it the other day and didn't see an icon on the nameplates when I had aggro.

**Comment by adamjedlicka** [comment]
It shows orange border around nameplates when you don't have aggro.

**Comment by reddy89** [comment]
Could we get an option for the inverse of that? Also an option for an icon on the nameplate as well?
