### ISSUE TITLE
ActionBars - Sometimes unable to change skills on LAS

### ISSUE THREAD

**Issue by adamjedlicka** [ForgeUI/ForgeUI#209]
Most of the times happens on alts. Probabbly some issue with saving settings (potion, mount or path ability) ?

**Comment by Hysteriana** [comment]
yeah got the same problem on my alt. need to deactivate action bar to change / regroup skills

**Comment by Skorp11** [comment]
u can easily fix it. reset the action bar addon via the "reset settings" once. 
when u open the forgeui options, klick on "addon" to open the forgeui addons tab. there u can reset this one addon.

**Comment by jcdenton2k** [comment]
Yeah this is related to saving Potions & Path for characters.
If you copy and paste the settings from your main, then the Potion & Path variables return an invalid value and result in this bug of being unable to change LAS.

The workaround for invalid potion value is to remove all potions from your inventory (stick them in bank) to clear that value out. 
The workaround for Path is to choose same path for main & alts.  Not ideal but it works if it is just a bank alt or something.

If we can get the 'saved path skill' values for all paths then we can manually edit the saved file and copy/paste the correct 'expected' value.

IDEALLY the easiest way to do this is to NOT save the current potion/path skill at all and have the players manually set it up each time they login.  It may irk some people but would completely negate this bug.

We are in desperate need of a ForgeUI update.  Please don't let this die O_O

**Comment by jcdenton2k** [comment]
WORKAROUND  to PREVENT this LAS bug from happening.

Before you copy your main's settings over to alts, be sure to do the following:
-Login to the alt so they get folders & settings INI files created for them
-Make the below edits to your ForgeUI_0_Char.xml in your AddonsSaveData directory

Edits for ForgeUI_0_Char.xml ;; open the file in WordPad or your fav text editor (not NotePad)
-Old:  <N K="nSelectedPotion" T="n" V="fivedigitnumber"/>
-New:  <N K="nSelectedPotion" T="n" V="0"/>

-Old:  <N K="nSelectedPath" T="n" V="fivedigitnumber"/>
-New:  <N K="nSelectedPath" T="n" V="0"/>

-Old:  <N K="nSelectedMount" T="n" V="fivedigitnumber"/>
-New:  <N K="nSelectedMount" T="n" V="0"/>

Just find those values and replace the existing five digit number with a 0 (zero) as shown above.
Save the file and NOW you can feel free to copy all your ForgeUI settings as you like ^_^

**Comment by jcdenton2k** [comment]
RESET SETTINGS if your LAS is bugged and you just want to fix it.
Open ForgeUI Options, Click Addons button, then click the ... next to ActionBars and click Reset Settings.

Picture here:
https://www.anony.ws/i/2015/12/10/ForgeUIActionBarReset.png

**Comment by jcdenton2k** [comment]
Mount limit on LAS - Potential workaround

**This is untested because I don't have 10+ mounts to test this myself**
**Backup any files before you change them**

1.  Open ForgeUI_Actionbars.lua with WordPad or your favorite text editor

2.  Search for this line:  if nCount < 10 then nCount = nCount + 1 end

3.  Replace the number 10 with any number you want higher than 10

4.  Save & close file, restart the game and test it out!

5.  I'll update or remove this depending on feedback that I receive.

6.  Feedback can be sent to: Myrla Everblade @ Entity-Exile or by posting here or on the Curse comments.

**Comment by adamjedlicka** [comment]
Fixed in v0.5
