### ISSUE TITLE
Hide unused action bar slots On Extra Action Bar 1 & 2 ?

### ISSUE THREAD

**Issue by GenericNameLol** [ForgeUI/ForgeUI#211]
It feels so clunky to have to show either all of the action bar or none at all, especially when you will rarely use all of the buttons at once.

Can it not be made to hide unused action bar slots so only those with something in them will show on the UI?

(Would also really be nice to give an easy way to make the action bars horizontal instead of having to meticulously adjust every single one)

**Comment by cengie** [comment]
Done, will probably be in the next update
