### ISSUE TITLE
Nameplate option

### ISSUE THREAD

**Issue by Anferny** [ForgeUI/ForgeUI#216]
Any way you can add a way to edit nameplate height? Thank you for the great addon package, I love it!

**Comment by Toludin** [comment]
You can do this now, in the Nameplate options. I believe right now the height and width options are accidentally reversed, but that will be fixed in a coming update.

**Comment by Anferny** [comment]
I found it, thank you!

Is there anyway to maybe split up nameplate options? What I mean is having enemy nameplate options separated from friendly.
