### ISSUE TITLE
Can't change my stance

### ISSUE THREAD

**Issue by NezzieSenpai** [ForgeUI/ForgeUI#225]
Is there anyway to do this on the fly? Because the only way I can figure out how to do it, is to remove the mod, change stance, then add it back in.. and that is a very large hassle.

**Comment by Peshyy** [comment]
Hmm, doesn't ForgeUI work with Right-Clicks? I mean, right click on the stance icon and it should bring the other stances. I haven't used ForgeUI in a long time so I can't say for sure, but I think that's how it works :)

**Comment by NezzieSenpai** [comment]
That worked! Thank you very much.

**Comment by Peshyy** [comment]
Ah, awesome! Glad I could help ^^

**Comment by BedDweller** [comment]
You can also keybind the stances in the default wildstar keybinder.
