### ISSUE TITLE
How do you hide Elements?

### ISSUE THREAD

**Issue by Mayooonaise** [ForgeUI/ForgeUI#227]
I know how to move them around but I'm using ForgeUI with PotatoUI so I don't need most of the things on the screen I just want to keep the bar at the bottom and the action bar on the right. The cast bars, target bars, player bar. I want to hide all of those

**Comment by adamjedlicka** [comment]
I don't remember the exact way but it should be under ESC > Addons . There you should be able to find ForgeUI addons and turn them off.
