### ISSUE TITLE
Error with NeedGreed

### ISSUE THREAD

**Issue by 2ooza** [ForgeUI/ForgeUI#228]
when Arcterra comes i got error:

Everytime when loot is droped, while im in group, i got ForgeUI_NeedGreed error and loot is gone.
Then i reloadui and i can see drop, but then when i choose Greed or Need - error is back

**Comment by 2ooza** [comment]
...dStar\Addons\ForgeUI_NeedGreed\ForgeUI_NeedGreed.lua:342: attempt to call method 'GetChatLinkString' (a nil value)
stack trace:
	...dStar\Addons\ForgeUI_NeedGreed\ForgeUI_NeedGreed.lua:342: in function <...dStar\Addons\ForgeUI_NeedGreed\ForgeUI_NeedGreed.lua:341>

**Comment by olbat** [comment]
Just made a pull request #229 based on [ZodBain](https://forums.wildstar-online.com/forums/index.php?/user/800050-zodbain/)'s [patch](https://forums.wildstar-online.com/forums/index.php?/topic/150654-api-12-fixes-for-abandoned-addons/?p=1499010), hope it will help to get the addon working again ...

**Comment by adamjedlicka** [comment]
Does this fix work on live? If yes I can merge the request and release new version on curse.

**Comment by olbat** [comment]
I tested it quickly on live, no more errors when the Need or Greed window pops up.
