### ISSUE TITLE
API 12 not compatibile

### ISSUE THREAD

**Issue by Apteryxon** [ForgeUI/ForgeUI#232]
Whole addon doesn't with API12 version of Wildstar. Will it be updated? It's the best UI addon out there, it would be awfull to loose it

**Comment by adamjedlicka** [comment]
Maybe, maybe not. Probably yes, but not in next 2 to 3 weeks, due to incoming exams at uni.

**Comment by Apteryxon** [comment]
thank you for reply, I'm sure many people will appreciate it, specially with brand new wildstar on steam hype :)

**Comment by christopherjtaylor** [comment]
Thanks for all of your work @adamjedlicka. Really appreciate your work on this addon.

**Comment by Toludin** [comment]
I'll take a peek as well this weekend to see if I can get it functioning, if you aren't going to be able to look for a bit Adam.
