### ISSUE TITLE
Error preventing inventory opening.

### ISSUE THREAD

**Issue by duckboi101** [ForgeUI/ForgeUI#239]
I'm using 0.5-beta.
`...ar\Addons\ForgeUI_Inventory\ForgeUI_InventoryBag.lua:177: attempt to call field 'API_RegisterAddon' (a nil value)
stack trace:
	...ar\Addons\ForgeUI_Inventory\ForgeUI_InventoryBag.lua:177: in function <...ar\Addons\ForgeUI_Inventory\ForgeUI_InventoryBag.lua:170>`

**Comment by adamjedlicka** [comment]
Inventory is not in v0.5 yet. Just delete it for the moment.
