### ISSUE TITLE
What are these red lines on my unit frames?

### ISSUE THREAD

**Issue by Jeffroiscool** [ForgeUI/ForgeUI#240]
![image](https://cloud.githubusercontent.com/assets/4972345/16619715/a122c066-438f-11e6-9ad7-221795a59831.png)

I have no idea what these are aand where I can change them.

**Comment by adamjedlicka** [comment]
This is PvP indicator. You can turn it off in UnitFrames options. But if you dont like it let me know. I personally dont know what to use as a PvP indicator so it looks good and is in style of other ForgeUI elements.

**Comment by Jeffroiscool** [comment]
Alright, thanks. It will bug out indeed.
Another option to indicate PVP could be like a little icon somewhere. The line just looks a little too random to my liking :)

I like how much stuff you're adding to ForgeUI though, I'm basically checking here multiple times a day and updating my build here :P

**Comment by Jeffroiscool** [comment]
What about using a fake PvP buff icon? That might work :D

**Comment by adamjedlicka** [comment]
Yeah I was thinking about little red flag in he corner of unitframe but I haven't found nice icon yet.
