### ISSUE TITLE
Change focus bar color at certain thresholds

### ISSUE THREAD

**Issue by Jeffroiscool** [ForgeUI/ForgeUI#242]
There used to be an option to make the focus bar red whenever you reached 30%.
Can you add it back in (and maybe put in the option to customize as well)?

**Comment by adamjedlicka** [comment]
Yeah I will add it back. This is one of the options that got lost in development.

**Comment by Mischh** [comment]
Thank you for your Suggestion!
The changes were made in this commit: f15deb37b49e629a3e7232327d689113afd27f84

-Mischh
