### ISSUE TITLE
"Infinite Interrupt Armor" / "Immune" floating text

### ISSUE THREAD

**Issue by Jeffroiscool** [ForgeUI/ForgeUI#243]
Hey there, it seems that the new ForgeUI keeps spamming "Infinite Interrupt Armor" and "Immune" as a floating text a lot. Is there an option to turn it off? If not, please make one :)

You can see what happens in this video (the orange text): https://youtu.be/XsCWSVGCb14?t=109

**Comment by adamjedlicka** [comment]
Fixed in v0.5.1
