### ISSUE TITLE
ActionBars - Extra & user defined bars and buttons

### ISSUE THREAD

**Issue by adamjedlicka** [ForgeUI/ForgeUI#246]

**Comment by lgorniak** [comment]
Hi there. Any updates on this?

**Comment by adamjedlicka** [comment]
I was not home lately so a bit of delay but working on it.

**Comment by adamjedlicka** [comment]
v0.5.4

**Comment by lgorniak** [comment]
Awesome thanx

**Comment by adamjedlicka** [comment]
Btw its separate addon: https://mods.curse.com/ws-addons/wildstar/248011-forgeui-actionbars-extended v0.5.4 is required for it to work.
