### ISSUE TITLE
Request: ActionBar table availability

### ISSUE THREAD

**Issue by Mischh** [ForgeUI/ForgeUI#248]
I know this sounds strange, but all i request is making the table `tBars` within ForgeUI_ActionBars.lua available from outside the file.
Something like `:GetBar(strKey)` or as a simple entry of the addon-object itself.

I am currently on fixing a very long outdated addon, from which i'd like to gain access to the bars/buttons to add frames as children.

Thank you - Mischh

**Comment by adamjedlicka** [comment]
Sure can do. Are you fixing skill switch?

**Comment by adamjedlicka** [comment]
Btw if you know how git/github works you can create pull request and make your own API.

**Comment by Mischh** [comment]
Yes. SkillSwitch. Somebody from my Guild found it and asked me months ago. Back then i added ForgeUI support. But scince your ActionBars were reworked completely i was asked to look back into it. I made it work with a horrible workaround. The Addon itself works perfectly, but it never had ForgeUI support.

**Comment by adamjedlicka** [comment]
OK I added method called _API_GetTBars_ so you can use it for example like this:
````lua
Apollo.GetAddon("ForgeUI_ActionBars"):API_GetTBars()
````
I'll release new version of ForgeUI later today.
