### ISSUE TITLE
Make actionbar divideable

### ISSUE THREAD

**Issue by Jeffroiscool** [ForgeUI/ForgeUI#249]
I had people in my guild complaining they couldn't move the individually skills from the action bar any more.

Can you make an option to add that back?

**Comment by adamjedlicka** [comment]
Duplicate with #246 

Tommorow I'll start working on it. I'll do it probabbly as an additional addon which allows you to create custom bars/button which you will be able to place wherever you want and fill it with whatever you want.

**Comment by Jeffroiscool** [comment]
Oops, sorry for the duplicate

**Comment by adamjedlicka** [comment]
Not a problem.
