### ISSUE TITLE
ForgeUI Ver. 0.5.1-a Bug Issues/Opinion on Changes.

### ISSUE THREAD

**Issue by OfficialOkaton** [ForgeUI/ForgeUI#250]
So, I'm fairly new to Wildstar (Dominion Spellslinger represent), but fell in love with ForgeUI Instantly due to its similarity and usefulness like ElvUI was for WoW.

I did use the previous version for a while to, I was so thankful for this update but miss a few things from the old one. Currently the only bug I noticed was when Unlocking Elements, it won't allow me to right click to adjust it more precisely, now I don't know if that's just me or not. Profiles are a bit buggy as well. All my old setups were deleted with the new update but now it'll be easier than spending 30-60min fixing each UI every time I make a new character.

Also, I gotta complain about the new grid option and Elements outline. It's a bit harder to see now while moving, even with the background option, the resizing of the grid part is much better though <3. It's harder to see where I'm moving my elements now cause the red outline is gone, if that could be optional to people who like to be precise, like myself, that'd be great.

Overall, I really love it and am enjoying my game play much better with it as I journey on through Wildstar.

**Comment by Jeffroiscool** [comment]
I noticed that the rightclick doesn't work at all. It would be nice if you could rightclick an element and could then directly key in X and Y coordinates and maybe give little arrows to move them around pixel perfect :)

**Comment by OfficialOkaton** [comment]
It was in the previous version that you could be able to, it may have got lost in the updates like some other features that were pointed out to be lost. Hopefully it's fixed soon.

**Comment by adamjedlicka** [comment]
Yeah I forgot about it when I was doing v0.5 But it is now in v0.5.2 which has just been released.

**Comment by OfficialOkaton** [comment]
Looks great, still iffy on the Element boxes, with no visible outline it's hard to be precise, can't put in custom x and y coord makes it iffy too, hopefully those features come back. Other than that I haven't found anymore bugs or changes that make it hard to use.
