### ISSUE TITLE
Mount - selection (bug)

### ISSUE THREAD

**Issue by Ethaw** [ForgeUI/ForgeUI#259]
I recently got the data drifter from avatus, but it doesn't appear in the mount selection menu. 
I have no problem when I disable forgeui though. 
I could also use the drifter when modifying manually my .xml settings with the mount ID, but it still didn't appear in the selection menu anyway after I changed for another mount.

**Comment by adamjedlicka** [comment]
You can scroll in mount select menu. Did you try that?

**Comment by Ethaw** [comment]
Ok, I feel like a noob now. Thanks.

**Comment by adamjedlicka** [comment]
:D
