### ISSUE TITLE
Tapcast issue when DPSing dummie

### ISSUE THREAD

**Issue by Jeffroiscool** [ForgeUI/ForgeUI#261]
`...tar\Addons\ForgeUI_Nameplates\ForgeUI_Nameplates.lua:992: attempt to index field 'tTapCast' (a nil value)
stack trace:
	...tar\Addons\ForgeUI_Nameplates\ForgeUI_Nameplates.lua:992: in function <...tar\Addons\ForgeUI_Nameplates\ForgeUI_Nameplates.lua:977>`

Fix please :D

**Comment by veex-ua** [comment]
what class are you playing when you getting this error?

**Comment by Jeffroiscool** [comment]
Slinger :)
