### ISSUE TITLE
ActionBars - can't change las [bug]

### ISSUE THREAD

**Issue by Ethaw** [ForgeUI/ForgeUI#264]
cf title, I'm unable to change my las. I disabled every addon except forgeui and forgeui_actionbars and the problem still persists. If I disable all addons and play vanilla, I don't have the issue. So 100% sure the problem comes from this addon.

I already had this problem  before and was able to solve it by doing weird things (among which the obvious, reloadui, relogging, and not so obvious, removing trinket, which a guild mate told me about...). But this time the problem persists and I can't get rid of it. It only affects 1 of my characters.

Interestingly, when I put back all my addons, 'builder' (which allows LAS switching) can still change my LAS among the ones I saved before (but I still can't modify anything anymore manually when going in my action set builder).

**Comment by adamjedlicka** [comment]
Do you remember what you did to cause this? I know about this bug, but it happens to only few ppl and I was never able to replicate it so I'm almost unable to fix it. I know in v0.4 it was mainly caused by copying profiles. You select path/potion, copy profile to another character and because path/potion which is unavailible on this character is selected, it locks the LAS. This no longer applies in v0.5 because mount/path/potion are character specific.

Maybe read more into Carbines ActionBars if there are some event listeners for this stuff or something?

**Comment by adamjedlicka** [comment]
Got this message from guildee:

> the actionbar bug i'm having might be related to path switching
i had the bug now while being scientist, swapped back to soldier and it started working again
it still worked with default actionbars while being scientist though

Is it possible to switch paths now? That may be one cause of this bug.

**Comment by adamjedlicka** [comment]
````lua
local hookee = ActionSetLib.RequestActionSetChanges
ActionSetLib.RequestActionSetChanges = (function(tAbilities)
    local tPathAbilities = AbilityBook.GetAbilitiesList(Spell.CodeEnumSpellTag.Path)
    local bFound = false;

    for _, pathAbility in ipairs(tPathAbilities) do
        if pathAbility.nId == tAbilities[10] then
            bFound = true
            break
        end
    end

    if bFound == false then
        tAbilities[10] = 0
    end

    return hookee(tAbilities)
end)
````

This snipped looks like working Workaround for locking LAS due to change of Path. Whenever path is changed it resets selected path ability.

**Comment by Ethaw** [comment]
The character on which I had the bug was a copied profile indeed, but before the action bar rework. I was used to the las lock on copying profile and just resetted the action bar settings of forgeui (which is now not possible anymore, we only have a global reset btw). But the bug sometimes comes back like it did a few hours ago, and somehow it disappeared the same way (despite not changing my addons, settings, anything - just playing a bit and relogging).
I wished I had more information about this bug happens!

**Comment by veex-ua** [comment]
Try to unequip your gadget and then change LAS next time you'll get this bug. Pretty sure it is somewhat related to gadgets.

**Comment by Ethaw** [comment]
Yeah I know this trick (though it's a weird one) but it didn't work this time. The bug disappeared on its own anyway... but finding the real cause would be nice.

**Comment by Ethaw** [comment]
Ok so the bug came back again, I got pissed off this time...
- the problem comes from the actionbars addon
- resetting the settings (unfortunately it resets EVERYTHING) removes the bug

So I opened the .xml file and tried to reset manually some settings to find where the issue was from. After some tries I found that removing this: (part of   <N K="ForgeUI_ActionBars" T="t"><N K="char" T="t">) removed the bug (well, for the moment, since I just did it, if the bug comes back again somehow, I'll post again).

                <N K="Ellone V - Jabbit" T="t">
                    <N K="nSelectedPath" T="n" V="46803"/>
                    <N K="nSelectedMount" T="n" V="71061"/>
                    <N K="nSelectedPotion" T="n" V="81926"/>
                </N>

**Comment by adamjedlicka** [comment]
Ineteresting. Thanks for the info. Did the lock of LAS happened out of nowhere or did you cahnge path/mount/potion and that caused the lock? Or did you change path completely? I just don't get it why would it lock itself without changing anything. Maybe IDs for path is dynamically chaning for some reason?

**Comment by adamjedlicka** [comment]
Also next time if you LAS locks up again, try switching your path skill/mount/potion. I managed to lock my LAS and fixed it this way.

**Comment by Ethaw** [comment]
I can't say for sure about when it happened, since it could have happened a while before (I have las presets with 'builder' so I rarely change my las manually, and somehow 'builder' bypasses the bug). It might be when I unlocked soldier (I was scientist), but take this with a grain of salt. Also, I tried changing my path and stuff... but when I just unlocked soldier, I had none :D so maybe the issue was that forgeui had the ID of a scientist spell that I couldn't use.

**Comment by zaery** [comment]
> I can't say for sure about when it happened, since it could have happened a while before (I have las presets with 'builder' so I rarely change my las manually, and somehow 'builder' bypasses the bug). It might be when I unlocked soldier (I was scientist), but take this with a grain of salt. Also, I tried changing my path and stuff... but when I just unlocked soldier, I had none :D so maybe the issue was that forgeui had the ID of a scientist spell that I couldn't use.

Same situation here, especially with the builder addon still working. I thought I switched mount/skill before with no change in the lock, but I'll try again, and try that fix tonight.
