### ISSUE TITLE
Nameplates - Castbar text design

### ISSUE THREAD

**Issue by veex-ua** [ForgeUI/ForgeUI#274]
Currently considering removing "center castbar text" option and keep castbar text centered below castbar by default. This will allow for castbar text width to be increased to better support displaying long cast names (i.e "Physic Frenzy (3/4)", "Transmating to Thayd" etc) without text auto-scalling kicking in. Can keep this option and play with castbar text anchors instead but I really doubt anyone will miss non centered castbar text.

**Comment by adamjedlicka** [comment]
Sure. Do whatever you think is the best.
