### ISSUE TITLE
Nameplates - Targeted nameplate always on top

### ISSUE THREAD

**Issue by veex-ua** [ForgeUI/ForgeUI#276]
From closed issue, this one is really needed. Any idea where to start looking? Guess it has something to do with HUD Stratum?

**Comment by adamjedlicka** [comment]
Yup. If you want to move nameplate over the top of every other nameplate, you have to destroy it and create new in different stratum F:API_GetStratum or you can use nil as a stratum (highest possible). Maybe there is a method to change parent of window but I haven't find it yet.
