### ISSUE TITLE
Nameplates - Guild members with non-guild tag aren't colored with guild color

### ISSUE THREAD

**Issue by adamjedlicka** [ForgeUI/ForgeUI#279]
Dunno if this counts as a bug, I would say yes. Or atleast it makes sense to color all guild memebers with guild color even if they don't have guild tag selected.

This could be solved maybe by comparing unit to the list of online guild members instead of comparin gtags? Is it even worth doing? If I recall correctly carbine nameplates also don't color guild members without guild tag.

**Comment by veex-ua** [comment]
Hmm, apparently you can't trust carbine's API docs even for simple stuff:
```
GetGuildName()
Description
Returns the unit's guild's name. Note that this will specifically get the guild and not other guild types such as warparties, circles, or arena teams.
```
Anyways, I'll take a look.
