### ISSUE TITLE
Nameplates - Bar visibility settings not applied

### ISSUE THREAD

**Issue by SirLagardere** [ForgeUI/ForgeUI#281]
Hello,
When I set the bar visibility to never (to friendly and hostile player), almost every time in combat, they appear. No error logged.
Hope you could track down this issue.
Regards

**Comment by veex-ua** [comment]
I can't reproduce this issue. For me bars never appears despite combat state. Maybe this is due some combination of settings. I'll need you to upload your settings file on any file hosting service and tell me on which profile you are having this issue.

..\AppData\Roaming\NCSOFT\WildStar\AddonSaveData\[Some folder with hash code]\ForgeUI_0_Acct.xml

**Comment by SirLagardere** [comment]
I've uploaded the file and you could get it here : [http://www.filehosting.org/file/details/590131/ForgeUI_0_Acct.xml](url)
I've noticed the issue on two profiles : "Cinedelle Lightbringer - Jabbit" and "Cine PvP".

**Comment by veex-ua** [comment]
So I've tested on your profile settings and everything work as intended.

"Cinedelle Lightbringer - Jabbit"
Friendly player is set to "never" but "hide on full hp" option enabled means nameplates are shown when unit isn't full health. (wording on "hide on full hp" option a bit confusing, it's more like "show when not full hp")
Hostile player is set to "never" and they never appear as expected.

"Cine PvP"
Hostile player is set to "always" and "hide when not flagged for PvP" option enabled means that you will see nameplates only for PvP flagged hostile players.
Friendly player is set to "out of combat" and "track player combat state" option enabled means that nameplates are only shown when player (you) is out of combat.

**Comment by SirLagardere** [comment]
Oh I see... my bad. Thanks for your clarification :) the main point was, as you said, the "hide on full hp", it's a bit confusing, and I admit... I need to really read the help text on mouse over ^^
Thanks for your time, and keep up the good work on this great addon suite !
