### ISSUE TITLE
Player / enemy info frame error

### ISSUE THREAD

**Issue by TWEEKARNYCM** [ForgeUI/ForgeUI#282]
...ildStar\Addons\ForgeUI_ToolTips\ForgeUI_ToolTips.lua:66: Usage: PostHook([object], method, [handler]): Attempting to hook a non existing target
stack trace:
	[C]: in function 'error'
	...ar\Addons\ForgeUI\libs\GeminiHook\GeminiHook-1.0.lua:185: in function 'hook'
	...ar\Addons\ForgeUI\libs\GeminiHook\GeminiHook-1.0.lua:284: in function 'PostHook'
	...ildStar\Addons\ForgeUI_ToolTips\ForgeUI_ToolTips.lua:66: in function 'ForgeAPI_Init'
	...Roaming\NCSOFT\WildStar\Addons\ForgeUI\core\core.lua:150: in function 'InitAddon'
	...Roaming\NCSOFT\WildStar\Addons\ForgeUI\core\core.lua:362: in function 'Init'
	...a\Roaming\NCSOFT\WildStar\Addons\ForgeUI\ForgeUI.lua:125: in function 'OnCharacterCreated'
	...a\Roaming\NCSOFT\WildStar\Addons\ForgeUI\ForgeUI.lua:119: in function <...a\Roaming\NCSOFT\WildStar\Addons\ForgeUI\ForgeUI.lua:83>

**Comment by veex-ua** [comment]
Was the carbine default "ToolTips" addon enabled when you got this error?

**Comment by TWEEKARNYCM** [comment]
Nah, seems like that was the error.

Thanks!
