### ISSUE TITLE
Nameplates - Anti-heal debuff indicator

### ISSUE THREAD

**Issue by adamjedlicka** [ForgeUI/ForgeUI#289]
So apperently there is new debuff in RMT which when applied eats up incoming heals up to certain number. There is visual indicator in default nameplates so I think ForgeUI should have it to.

Laveka and adds on the 2nd room from the start of RMT should apply this debuff.

**Comment by GreatTeacherOni** [comment]
wouldn't it be awesome to show that debuff as an icon? so it would be part of the #286 case. is the debuff dispellable?

**Comment by adamjedlicka** [comment]
Yeah I was thinking about it, but CKJester informed me that its really required to be a bar proportional to health to be really useful for proper raiding.

And yes, it works that it soaks for example 20k healing. So until you heal those 20k you heal that debuffed player for 0.

**Comment by veex-ua** [comment]
Apparently there is also some kind of health clamping mechanic. The code is in PTR nameplates addon:
```lua
local nHealingAbsorb = unitOwner:GetHealingAbsorptionValue()
local nHealthClampMin = unitOwner:GetHealthFloor()
local nHealthClampMax = unitOwner:GetHealthCeiling()
```
