### ISSUE TITLE
API 13

### ISSUE THREAD

**Issue by Zod-** [ForgeUI/ForgeUI#292]
With the latest patch on the PTR (2 hours ago) they bumped the API version to 13. I didn't see anything break yet so I assume it was just a technicality after the recent API changes for MultiQueue and the RMT release on the 17th.

**Comment by adamjedlicka** [comment]
Yeah it looks like nothing big changed or atleast everything works on PTR. I'll bump the API version and release new ForgeUI when RMT hits live.
