### ISSUE TITLE
ActionBars - bug with show option

### ISSUE THREAD

**Issue by Ethaw** [ForgeUI/ForgeUI#294]
The action bar still shows after a reloadui / relogging even though I unchecked the 'show' option.

**Comment by adamjedlicka** [comment]
Which action bar? All of them or only the main "Action bar" one?

**Comment by veex-ua** [comment]
All of my bars remain hidden after reloading UI if 'show" option is unchecked.

**Comment by Ethaw** [comment]
Only the main one. But for some reason (I didn't change any addons or anything) now the bug doesn't happen anymore...

**Comment by Ethaw** [comment]
The only thing I changed is using 'action bars ext' (the reason why I wanted to hide the base forgeui actionbar), so maybe there was a conflict somewhere.

**Comment by adamjedlicka** [comment]
I remember fixing this bug for the main action bar few versions back. It's possible you had old version of ForgeUI.
