### ISSUE TITLE
Cant save changes after RMT, reinstall doesnt work

### ISSUE THREAD

**Issue by freakyfly** [ForgeUI/ForgeUI#300]
Hi has a real problem, cant change something.... 
 
Id like to use this addon for a year, but after RMT patch, i cant change any settings, and lost all of my saved profiles...
 
Ill try to reinstall addon for a 30 times, any variations. From curse, from a folder, and install from curse manual/ auto/ github.... i dont know whats going on, but its still dont work =( 
 
Please help me, i cant play without this addon.. ((

**Comment by Jeffroiscool** [comment]
Did you try removing the saved files from addonsavedata?

The most important file is located in %appdata%\NCSOFT\WildStar\AddonSaveData\[charnamewithnumbers]\

In here you can find a called ForgeUI_0_Acct.xml
Try to remove this file.

**Comment by freakyfly** [comment]
doesn't help =(

**Comment by adamjedlicka** [comment]
Uninstall all addons. Then install only ForgeUi And try if it works. If yes then install rest of the addons.

**Comment by freakyfly** [comment]
Thanks so much... it helps,
