### ISSUE TITLE
Nameplates - Overlapping Chat

### ISSUE THREAD

**Issue by firegore** [ForgeUI/ForgeUI#301]
Since the new Nameplates Change in one of the latest Builds, the Nameplates are overlapping the Chatwindow.

**Comment by Mischh** [comment]
Scince this was declared a bug: Moved to `InWorldHudStratum`.
Previously was on `FixedHudStratumLow` - the same as the ChatLog.
Adressed in this commit: 7e182dd604b5627eb2c18c5441d0554ef1b29cbf

-Mischh
