### ISSUE TITLE
Size of the Castbar Duration / Amount (on Tapcast Spells)

### ISSUE THREAD

**Issue by rubyi** [ForgeUI/ForgeUI#304]
Is it possible to adjust the size of the castbar duration / amount on TapCast spells? I want to make it bigger, so its easier visible for me.
Here a screen of  what i'm talking about.
http://imgur.com/a/3jo5r

![castbar](https://cloud.githubusercontent.com/assets/22036965/18288801/2aea922e-747d-11e6-931a-dbdd1ab21411.png)

**Comment by veex-ua** [comment]
Currently not possible but should be pretty easy to add these options. I'll take a look at this closer to weekend.

**Comment by rubyi** [comment]
i would appreciate that. It's hard for me to see those tiny bars, but i think they are quite important for a clear rotation (atleast for slingers).

**Comment by veex-ua** [comment]
I've added these options and they should be included in next version release. You can also download it from [here](https://github.com/ForgeUI/ForgeUI/tree/ui/tweaks) if you don't want to wait for the release.

**Comment by rubyi** [comment]
Thanks alot for the fast reply, unfortunately it doesn't work at all. My castbar is fully gone and it's not listed in the forgeUI options/interface anymore.
Do i have to replace sth else? i replaced all three "castbar" files

**Comment by veex-ua** [comment]
Closed via #305
