### ISSUE TITLE
Manual Installation issues - Patch 1.6.1

### ISSUE THREAD

**Issue by falt4rm** [ForgeUI/ForgeUI#311]
Hello there,
Since the last patch i can't make ForgeUI to work ;( - 
Tried several ways to fix it : 
- Dump Addons folder
- Remove all addons except ForgeUI + modules

Still same errors appearing - I checked Geminidb - but can't figured out a fix.
ForgeUI installed is the last Github version available.

Here is the log errors :

`cannot open C:...\AppData\Roaming\NCSOFT\WildStar\Addons\ForgeUI\libs\GeminiDB\GeminiDB-1.0.lua: Result too large

cannot open C:...\AppData\Roaming\NCSOFT\WildStar\Addons\ForgeUI\libs\CallbackHandler\CallbackHandler-1.0.lua: Result too large

cannot open C:...\AppData\Roaming\NCSOFT\WildStar\Addons\ForgeUI\libs\GeminiEvent\GeminiEvent-1.0.lua: Result too large

cannot open C:...\AppData\Roaming\NCSOFT\WildStar\Addons\ForgeUI\libs\GeminiHook\GeminiHook-1.0.lua: Result too large

...Roaming\NCSOFT\WildStar\Addons\ForgeUI\core\core.lua:17: attempt to index a nil value
stack trace:
    ...Roaming\NCSOFT\WildStar\Addons\ForgeUI\core\core.lua:17: in main chunk

...aming\NCSOFT\WildStar\Addons\ForgeUI\core\movers.lua:425: attempt to call method 'API_NewModule' (a nil value)
stack trace:
    ...aming\NCSOFT\WildStar\Addons\ForgeUI\core\movers.lua:425: in main chunk

...Roaming\NCSOFT\WildStar\Addons\ForgeUI\core\util.lua:174: attempt to call method 'API_NewModule' (a nil value)
stack trace:
    ...Roaming\NCSOFT\WildStar\Addons\ForgeUI\core\util.lua:174: in main chunk

...tar\Addons\ForgeUI\modules\forgecolor\forgecolor.lua:354: attempt to call method 'API_NewModule' (a nil value)
stack trace:
    ...tar\Addons\ForgeUI\modules\forgecolor\forgecolor.lua:354: in main chunk

...\WildStar\Addons\ForgeUI\modules\profiles_module.lua:104: attempt to call method 'API_NewModule' (a nil value)
stack trace:
    ...\WildStar\Addons\ForgeUI\modules\profiles_module.lua:104: in main chunk

...T\WildStar\Addons\ForgeUI\modules\credits_module.lua:122: attempt to call method 'API_NewModule' (a nil value)
stack trace:
    ...T\WildStar\Addons\ForgeUI\modules\credits_module.lua:122: in main chunk

...\WildStar\Addons\ForgeUI\modules\settings_module.lua:16: attempt to index a nil value
stack trace:
    ...\WildStar\Addons\ForgeUI\modules\settings_module.lua:16: in main chunk

...T\WildStar\Addons\ForgeUI\modules\welcome_module.lua:60: attempt to call method 'API_NewModule' (a nil value)
stack trace:
    ...T\WildStar\Addons\ForgeUI\modules\welcome_module.lua:60: in main chunk

...SOFT\WildStar\Addons\ForgeUI\modules\skins\skins.lua:116: attempt to call method 'API_NewModule' (a nil value)
stack trace:
    ...SOFT\WildStar\Addons\ForgeUI\modules\skins\skins.lua:116: in main chunk

...ldStar\Addons\ForgeUI\modules\skins\carbine\taxi.lua:10: attempt to call method 'API_GetModule' (a nil value)
stack trace:
    ...ldStar\Addons\ForgeUI\modules\skins\carbine\taxi.lua:10: in main chunk

`
Best regards,
Falt

**Comment by adamjedlicka** [comment]
Yeah you can't use that green download button on GitHub. Libraries are included as git-submodules and for some reason GitHub doesn't bundle them by default. So you will have to either download zip from releases page [https://github.com/ForgeUI/ForgeUI/releases](https://github.com/ForgeUI/ForgeUI/releases) or use this command: `git clone --recursive https://github.com/ForgeUI/ForgeUI.git`

**Comment by falt4rm** [comment]
I did what you suggested but couldn't make it worked - So i figured out if it wasn't your code and i had the correct package - it must be my Zip extractor (7zip) which was behind all this.
And yes it was 7zip - Self-extraction reported some errors during but nothing dramatic (missing readme.txt).
After reinstalling it - Extraction errors gone for some reasons.

Thanks for your time - It's all working.
Falt
