### ISSUE TITLE
ResourceBars - Esper issue with mental overflow

### ISSUE THREAD

**Issue by Ethaw** [ForgeUI/ForgeUI#312]
When generating & spending psi very fast (especially with rmt class sets), sometimes the mental overflow part of the resource bar keeps displaying charges even with psi <5 (the normal 1-5psi has no issue however).

**Comment by adamjedlicka** [comment]
I don't play esper so you will have to give me some more info. does it mean that if you have less then 5psi points mental overflow shouldn't be visible no matter what?

**Comment by Ethaw** [comment]
exactly. it's technically impossible, since MO actually acts like 6th and 7th psi point.
