### ISSUE TITLE
housing bar not visible

### ISSUE THREAD

**Issue by towerdog** [ForgeUI/ForgeUI#327]
i love this addon ive looked through all menus and checked all appropriate boxs but i still dont see my housing menu bar when im at my house please help 
thank you aain and great addon

**Comment by Mischh** [comment]
Scince this is a pretty old issue, I will close it.
If somebody has a little more Information on this Problem, please open another Issue.
The bar (which I assume you are missing) is called the 'Shortcut bar' in the current Settings.
This bar: http://i.imgur.com/CRPslHk.jpg

-Mischh
