### ISSUE TITLE
Issue extracting latest release

### ISSUE THREAD

**Issue by Koviko** [ForgeUI/ForgeUI#329]
When using 7-zip to extract the latest release, there seems to be an issue with [2 empty files by the same name as the directories: `libs` and `media`](http://i.imgur.com/DBMSoVU.png).

This causes an issue in 7-zip as it seemingly prioritizes those empty files and attempts to extract from them, causing it to [freeze with errors](http://i.imgur.com/rVnXnmx.png). The same issue occurs when downloading directly from Curse.

**Comment by adamjedlicka** [comment]
I'm unable to replicate this issue. What version of 7zip do you use? Also does it cause any complications? What about installing ForgeUI from curse client. That works?

**Comment by Koviko** [comment]
I'm using 7-zip version 9.20. It says "2010" on it, so perhaps I should consider updating. I'm not a user of Curse Client, so I can't confirm or deny whether it works there (though I imagine it does since the Curse page isn't full of complaints).

**Comment by Koviko** [comment]
I've upgraded 7-zip and the extraction works fine, now. So it appears that this issue is a 7-zip issue, not necessarily a ForgeUI issue. It's strange that 7-zip 9.20 has that issue, but maybe someone in the future who also didn't upgrade will benefit from this ticket.
