### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by Skarf80** [ForgeUI/ForgeUI#34]
Don´t know uf you are allready planning to implent this so if you are ignore thi :D

Could you plz add:
HP% on namplates
Class Color as an option for the Unit Frames
A bar on the Resource Bar to see how long your Innate iss Active
Options to resize the width and heigth amd the position of the Unit Frames per numbers (its really annoying to pull them in the same size and correct position to mirror them^^)

and last but not least add tooltips to the action bars

**Comment by adamjedlicka** [comment]
Added to issues
