### ISSUE TITLE
ForgeUI - Not saving settings

### ISSUE THREAD

**Issue by Prior99** [ForgeUI/ForgeUI#48]
When I do changes to the positions of the interface components in "Unlock UI" it is not saved. Whenever ui is reloaded or I click "save settings" it is resettet.

**Comment by Prior99** [comment]
Okay. Update: No settings are saved at all.

**Comment by adamjedlicka** [comment]
I know about this bug. When you preset 'Reset all settings' button in main window it will fix it. I have (hopefully) fix in v0.3.0.

**Comment by adamjedlicka** [comment]
What about now? Is it fixed?

**Comment by Prior99** [comment]
I did not yet have the chance to test as I switched back to the normal UI for the time being. I will test it tomorrow.
