### ISSUE TITLE
MiniMap - Error

### ISSUE THREAD

**Issue by perkolated** [ForgeUI/ForgeUI#52]
On mousing over a quest objective in zone map:

ui\ZoneMap\ZoneMap.lua:1522: attempt to index global 'PublicEventObjective' (a nil value)
stack trace:
	ui\ZoneMap\ZoneMap.lua:1522: in function 'OnGenerateTooltip'
	ui\ZoneMap\ZoneMap.lua:2791: in function <ui\ZoneMap\ZoneMap.lua:2786>

**Comment by adamjedlicka** [comment]
Not an issue of ForgeUI. ZoneMap is Carbine addon
