### ISSUE TITLE
ForgeUI - Special Bars not saving

### ISSUE THREAD

**Issue by Mae-Is-Mean** [ForgeUI/ForgeUI#70]
I think I've figured out WHY these specific bars never seem to save their location. I'm speaking specifically of the special bars that pop up only occasionally, like the housing bar, the vehicle bar, etc. Those bars are only moveable when they're available, so if you 'reloadUI' or save by some other means (camping) when they are not on your screen, their locations are removed and reset to default.

I think when we push the "Unlock elements" button, those bars should appear, even if we aren't in a state where they should be visible. This also goes for the pet window, which likes to move back to its default location too =( You also need to figure out how to keep those in the locations we set if we do a /reloadui when we aren't in a state where they are visible.

**Comment by adamjedlicka** [comment]
Appreciate the effort :) I will look at it when i get home.

**Comment by adamjedlicka** [comment]
v0.4.2
