### ISSUE TITLE
Problem with Food and Boost counter on buff bar

### ISSUE THREAD

**Issue by Bacon-21** [ForgeUI/ForgeUI#77]
It seems that it defaults to 9min for food and 4min for boosts....after it reaches those values it will stay at 0m until it reaches the actual 9min and 4min mark then it counts down correctly, respectively.  It might be a problem with just me but thought I would share.

**Comment by adamjedlicka** [comment]
This is not a bug. If your buff icons are too small it will cut out some numbers from remaining time. Just make your buff icons larger and everything will be ok.
