### ISSUE TITLE
ActionBars - Preventing LAS change

### ISSUE THREAD

**Issue by ARX-7** [ForgeUI/ForgeUI#78]
As stated on my lv 8 SS i cant change any AMPs/ Abilities unless i disable the Action bar

**Comment by adamjedlicka** [comment]
Does this bug persist if you restart the game? I know there is a bug with changing LAS in WildStar not associated with ForgeUI, so this might be it.

**Comment by ARX-7** [comment]
Yes, it is only on my slinger alt though, which is odd

**Comment by ARX-7** [comment]
Just hit 22, and it stopped being an issue
