### ISSUE TITLE
Unable to change skills on LAS

### ISSUE THREAD

**Issue by Xathonn** [ForgeUI/ForgeUI#82]
I'm unable to change the skills on my LAS, When I try and change something like changing an ability from t4 to t8 and hit use set it doesn't save it and just goes back to t4. Uninstalling forgeui makes it work again. From what I've heard it's an issue caused by copying forgeui's xml file in addonsavedata from one character to another. Is there a way to copy the UI from one character onto another without doing that?

**Comment by adamjedlicka** [comment]
Interesting, I'll look at it.

**Comment by adamjedlicka** [comment]
Found the issue. I will try to fix it. Atm you can fix it by changing your mount, recall, stance, potion and path skill.

**Comment by jrfried** [comment]
If this issue happened when trying to copy the ForgeUI_0_Char.xml to another character; switch characters or exit the game, edit the file, find and delete the  "<N K="nSelectedPath" T="n" V="*****"/>" line and the entire "<N K="PathButton" T="t">" section, all the way to the "</N>".

TBH, I'm not sure which one of these fixed the problem, but I've done the same method on 3 characters that had their LAS locked after copying the XML over to them and they are now fine.

You will have to re-do the positioning of your Path button though.

**Comment by adamjedlicka** [comment]
This fix solves exactly this. In ForgeUI settings is saved ID of your current path ability, so if you copy settings to another character with different path it will try to set your path ability to non-existent which locks your whole LAS. I will release this fixed version on curse soon, because it seems it doesn't cause any more trouble.

**Comment by adamjedlicka** [comment]
fixed in v0.4.0
