### ISSUE TITLE
ForgeUI - Allow sharing of UI settings

### ISSUE THREAD

**Issue by Xathonn** [ForgeUI/ForgeUI#99]
Something like a long code like perspective or AM use, Where if can copy it then paste it and it'll change the UI setting to that code

**Comment by adamjedlicka** [comment]
Great idea I'll look what I can do about it.

**Comment by codemasher** [comment]
Another thing i wanted to request. Would it be possible to add a load/save function, so that one would be able to load different settings for like support or assault?

**Comment by adamjedlicka** [comment]
Profiles will be in v0.5
